apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubefs
  name: kubefs
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30099
  selector:
    app: kubefs