apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubefs
  name: kubefs
  namespace: kubefs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubefs
  strategy: {}
  template:
    metadata:
      labels:
        app: kubefs
    spec:
      volumes:
      - name: media
        hostPath:
          path: /media/db
      containers:
      - name: kubefs
        command:
        - ./kubefs
        - serve
        - -p
        - "8080"
        - --dir
        - /media/db
        volumeMounts:
        - name: media
          mountPath: /media/db
        image: cmwylie19/kubefs:cascade
      serviceAccountName: kubefs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: kubefs
  namespace: kubefs
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubefs
  name: kubefs
  namespace: kubefs
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30099
  selector:
    app: kubefs
