apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kubefs-web
  name: kubefs-web
  namespace: kubefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubefs-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubefs-web
    spec:
      containers:
      - image: cmwylie19/kubefs-web
        name: kubefs-web
        ports:
        - containerPort: 80
        resources: {}