apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubefs-web
    version: v1
  name: kubefs-web
  namespace: kubefs
spec:
  ports:
    - port: 80
      name: http
      nodePort: 32217
  type: NodePort
  selector:
    app: kubefs-web