apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: server-prod
  namespace: argocd
spec:
  destination:
    namespace: kubefs
    server: https://192.168.1.214:6443
  project: default
  source:
    path: server/env/overlays/prod
    repoURL: https://github.com/cmwylie19/kubefs
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true

