name: Build/Push Action

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed

jobs:

  setup-build-push-deploy:
    needs: unit-test-backend
    name: build-containers-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push metrics-frontend
        uses: docker/build-push-action@v2
        with:
          context: ./metrics-frontend
          push: true
          tags: cmwylie19/blog-insights-frontend:latest


      - name: Build and push metrics-backend
        uses: docker/build-push-action@v2
        with:
          context: ./metrics-backend
          push: true
          tags: cmwylie19/blog-metrics-backend:latest


      - run: echo "🍏 This job's status is ${{ job.status }}."