name: Test Code on Push

on:
  # workflow_run:
  #   workflows: ["Check unsigned commits"]
  #   branches: [main]
  #   types: 
  #     - completed
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, edited, unlocked, review_requested]
    
jobs:
  check-commit-message:
    name: "check-commit-mesage"
    runs-on: ubuntu-22.04
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v1
        with:
          pattern: '\[(BUGFIX|DOCS|FEATURE|TASK)\] .+$'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  check-sign-off:
    needs: "check-commit-message"
    name: Write comment if unsigned commits found
    env:
      FORCE_COLOR: 1
    runs-on: ubuntu-22.04

    steps:
      - uses: live627/check-pr-signoff-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |- 
        cd server;
        GOARCH=arm64 GOOS=linux go build -o kubefs ./cmd/kubefs
    - name: Test
      run: |-
        cd server;
        ENV=CI go test -v ./...;
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      
    - name: Unit Test Frontend
      run: |-
        cd frontend;
        yarn -s;
        yarn run test-ci;
        echo "Exited with '$?'";

