# Promote a GitOps application from one environment to the next

name: On Promo

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      source_env:
        description: 'Source environment'
        required: true
        default: 'qa' 
        type: choice
        options:
        - stage
        - prod 
      target_env:
        description: 'Target environment'
        required: true
        default: 'staging' 
        type: choice
        options:
        - stage
        - prod 
      promote_container:
        description: 'Promote container tag'
        required: true 
        type: boolean 
        default: 'true'
      messsage:
        description: 'Commit message'
        required: true 
        type: string  
        default: '[TASK] Promote x.x.x to X'


jobs:
  promote:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Copy Frontend container tag
        if:  ${{ inputs.promote_container }}
        uses: canastro/copy-file-action@master
        with:
          source: "frontend/env/overlays/${{ inputs.source_env }}/version.yaml"
          target: "frontend/env/overlays/${{ inputs.target_env }}/version.yaml"

      - name: Copy Server container tag
        if:  ${{ inputs.promote_container }}
        uses: canastro/copy-file-action@master
        with:
          source: "server/env/overlays/${{ inputs.source_env }}/version.yaml"
          target: "server/env/overlays/${{ inputs.target_env }}/version.yaml"
       
      - name: Update Frontend Image Tag to remove Stage
        if: inputs.target_env == 'prod'
        run: | 
          sed 's/-stage//g' frontend/env/overlays/prod/version.yaml > frontend/env/overlays/prod/version1.yaml
          mv frontend/env/overlays/prod/version1.yaml frontend/env/overlays/prod/version.yaml 

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.messsage }}    
