name: Unit Test Action
# on: [push]
on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test-frontend:
    name: unit-test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Unit Test Frontend
        run: | 
          cd frontend;
          yarn -s;
          yarn run test;
          echo "Exited with '$?'"

  unit-test-backend:
    needs: unit-test-frontend
    name: unit-test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Unit Test Backend
        run: | 
          cd server;
          go mod tidy;
          ENV=CI go test -v ./...;
          echo "Exited with '$?'"

      - run: echo "🍏 This job's status is ${{ job.status }}."